### ISSUE TITLE
Activity 1.2 Meeting Preparation

### ISSUE THREAD

**Issue by dykesb** [sta518/discussion#1]
Congratulations on learning about markdown!  Post your screen snip/grab here and show off some of your skills.  For example:

- Try a gif: 

![GR Drive Drumline](https://media.giphy.com/media/1wQe4UF4ozNrhxZ3u1/giphy.gif)
- Try a [link](https://sta518.github.io)

Or you *might* want to **dress up** some `text`.

**Comment by adam-hubbell** [comment]
submission for adam hubbell
![STA518-markdown](https://user-images.githubusercontent.com/20645518/63720320-e6e64180-c81c-11e9-8166-25a848873bf0.png)
1. a list
2. **boldtext**
3. `code block`

**Comment by smbrougham** [comment]
![RMarkdown_week1](https://user-images.githubusercontent.com/36938589/63721105-966fe380-c81e-11e9-87aa-6fb83f859464.JPG)
### Markdown is cool
In *so many* ways. Here's a [quick reference](https://commonmark.org/help/).

**Comment by TonyTone1995** [comment]
![image](https://user-images.githubusercontent.com/45879343/63722053-6cb7bc00-c820-11e9-8bb3-448402fe1501.png)
### yeet
```{code
hello world and stuff
```
*  _this is a bullet point with italics_

**Comment by corinnejay** [comment]
![image](https://user-images.githubusercontent.com/54511119/63727604-d3dc6d00-c82e-11e9-8bfe-c123b691d4ab.png)

> **Markdown is cool**

*according to* @smbrougham

**Comment by maleym** [comment]
![activityprep1 2](https://user-images.githubusercontent.com/54540042/63730275-a2689f00-c838-11e9-800b-868685f46153.png)

**_Woohoo!_**

**Comment by KelArndt** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/54549172/63730596-f0ca6d80-c839-11e9-982d-f6e73809db66.png)

**wowza** *so cool*
_much fun_

**Comment by KenzieKo** [comment]
![Congrats snip](https://user-images.githubusercontent.com/54556255/63730441-4a7e6800-c839-11e9-8dce-4a818c5442df.PNG)

## **This was:** ##
-*Intersting*
-*cool*
-*quick*

**Comment by zyskabbie** [comment]
# Markdown is Cool
## Abbie Zysk 

![image](https://user-images.githubusercontent.com/54541090/63730671-43a42500-c83a-11e9-9cd4-00dc1ed4394e.png)

**Comment by dianagoodrich** [comment]
![image](https://user-images.githubusercontent.com/54555641/63730714-73ebc380-c83a-11e9-9c2d-ca3121549bc0.png)

**Comment by latackk** [comment]
# Katie Latack

![image](https://user-images.githubusercontent.com/54510880/63730675-47d04280-c83a-11e9-918a-fbb0bb995ca9.png)

**Fun stuff**
` code would go here`
*thanks*

**Comment by grismasinya** [comment]
![image](https://user-images.githubusercontent.com/43278942/63730813-d6dd5a80-c83a-11e9-8e49-a59b2d89b9aa.png)
**This**
 *was*
 # fun

**Comment by chitzinwin** [comment]
lovely
![image](https://user-images.githubusercontent.com/22484078/63732740-a5b55800-c843-11e9-833e-74266bec6f25.png)

**Comment by rbaxter231** [comment]
![Screen Shot](https://user-images.githubusercontent.com/51412803/63778270-7c7fe080-c8b2-11e9-9a10-88b3ffe23a6e.png "Rachel's Screenshot")

### I think **Markdown** documents are *cool*, 
but not as *cool* as my ***dog Gracie***.

![gracie](https://user-images.githubusercontent.com/51412803/63779044-e5b42380-c8b3-11e9-8300-6430664f6e76.jpg "Gracie Girl")
[Adopt Don't Shop](https://www.petfinder.com/)

**Comment by EricKirkendall** [comment]
<img width="632" alt="STA_418_CongratsScreen" src="https://user-images.githubusercontent.com/54581563/63779397-7be84980-c8b4-11e9-9536-a7af9367b1e8.PNG">

## Here is a list of things I learned:
--------
1. Ordered Lists
2. Nested
   - Lists
3. **Bold**
4. `Inline Code`

**Comment by edorn15** [comment]
![markdown_completion](https://user-images.githubusercontent.com/31247374/63785871-10f04000-c8bf-11e9-8e6c-eb4588f98601.png)

**One of my favorite quotes** by Eleanor Roosevelt is:

> The future belongs to those who believe in the beauty of their dreams.

You can find other Eleanor Roosevelt quotes [here](https://www.brainyquote.com/authors/eleanor-roosevelt-quotes). :blush:

**Comment by harmans97** [comment]
![image](https://user-images.githubusercontent.com/54410625/63790474-56187000-c8c7-11e9-9e04-1cfa1bafa15c.png)
 
**Bolded text**
## level one heading 
Martin Luther King Jr. quoted: 
>The time is always right do do what is right
:clap: 
:whale:

**Comment by despresj** [comment]
![Screen Shot 2019-08-27 at 12 39 46 PM](https://user-images.githubusercontent.com/54477023/63790809-1736ea00-c8c8-11e9-8057-c2200a762cbc.png)
#`well that was fun` 
what have we [here](https://www.google.com/)
_DONE_

**Comment by ortizel** [comment]
![Congratulations](https://user-images.githubusercontent.com/54406443/63804287-b4475200-c8cb-11e9-9c1a-3ac24024c7af.png)

## Hello

**Comment by PorterSmash** [comment]
![image](https://user-images.githubusercontent.com/37052182/63814150-e40f4d80-c8fd-11e9-8a6b-8c6755e9404a.png)

*Here is my image*
**but don't shout, it get's scared easily**
# Instructions
* Approach slowly
    1. Quiet feet
    2. Low to the ground
* Introduce yourself
    1. Let it smell your hand
    2. Wait till it's finished
* Pet it gently
![image](https://d32l83enj9u8rg.cloudfront.net/wp-content/uploads/sleeping-kitten-TS_160626325-1.jpg)

**Comment by nlj2014** [comment]
![Markdown](https://user-images.githubusercontent.com/54484028/63816485-4c622d00-c906-11e9-8c5b-0d4d12e30584.PNG)
*Hello*
Markdown is **awesome**
Quote of the day
>Would I rather be feared or loved. Easy, both. I want people to be afraid of how much they love me.

Michael Scott
![](https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif)

**Comment by annie5696** [comment]
![screenshot](https://user-images.githubusercontent.com/54519762/63817956-ba115780-c90c-11e9-97cc-3a5043b80b9c.PNG)

**Comment by shyaa23** [comment]
![done](https://user-images.githubusercontent.com/35463392/63817961-baa9ee00-c90c-11e9-9e8c-beec839bdb56.PNG)

**Comment by danno3321** [comment]
![Markdown Tutorial Complete Screenclip](https://user-images.githubusercontent.com/45361485/63819070-d8c61d00-c911-11e9-9cf4-7b31c5405eeb.png)

# Hello!

To be honest, I'm not _quite_ sure what else to put here. So... Uh...

__Guess I'll just have to _improvise_!__

Let's see... What can I try... ```What was that assignment again?```
> Showcase some of your new skills (e.g., formatted text, inline code, hyperlinks, tag a classmate) or try some gifs or emojis.

### Okay, so maybe something like:
1) Some in-line code?
    * Nah, not sure what to write code about right now, and I don't feel like stealing it off the internet.
    * \*Looks at tutorial again\* \*_Remembers what in-line code actually refers to_\* Oh... Guess I already did that one...

    ![Oops! The gif failed to load!](https://media.giphy.com/media/3ov9jCGzR1JtD8Hlni/giphy.gif)


2) A gif or image?
    * Well, I already have a gif, so I guess I'll post one of my favorite memes?

    ![Fireball meme](http://images3.memedroid.com/images/UPLOADED189/5c9f162f27870.jpeg)

    * Here's a [link](https://www.reddit.com/r/dndmemes/) to the dnd memes subreddit if anyone wants to find more memes like this.



3) ...
    * .....
    * ........
    * ..............
    * Shouldn't there be a third thing? Oh wait, it looks like I've already covered just about every category in the tutorial. 

Well, I guess I'll leave it here for today then!
-Adam Weaver, Section 1

**Comment by hawkeral** [comment]
<img width="1171" alt="Screen Shot 2019-08-27 at 9 58 06 PM" src="https://user-images.githubusercontent.com/54479633/63820100-0319d980-c916-11e9-9b4d-1358fc540643.png">

**:)**

# To Do:
- eat
- sleep
- ????
- profit

Here's a good time waster: [The Useless Web](https://theuselessweb.com/)

**Comment by abanninga** [comment]
![image](https://user-images.githubusercontent.com/54563251/63820423-27c28100-c917-11e9-93c3-677ad503b651.png)

*we* **out** ```here```

here's a [link](http://www.zarias.com/cute-puppies/) to cute puppies

**Comment by mattphad** [comment]
# Markdown picture:
<img width="1257" alt="Screen Shot 2019-08-27 at 10 04 46 PM" src="https://user-images.githubusercontent.com/54512739/63821115-cc45c280-c919-11e9-8279-cea3d79e0e70.png">

As you can see, I'm a fan of:
     _YouTube_
    **Twitter**
    [The Ringer](theringer.com)

~~Thanks~~ Bye

**Comment by Carl-Wilson96** [comment]
![markdownend](https://user-images.githubusercontent.com/54507449/63877451-a827c700-c995-11e9-930a-dc2a52c86622.png)

_Markdown_ is pretty neat.
My favorite things about it are:

1. Making Lists
2. Adding [Links](https://commonmark.org/help/) for reference.

**Comment by SBennett95** [comment]
<img width="1168" alt="Screen Shot 2019-08-28 at 1 59 17 PM" src="https://user-images.githubusercontent.com/54493433/63880801-6fd7b700-c99c-11e9-8e2b-03c0410dfd60.png">

- Just learned about **Markdown**
- For fun I like to play [online chess](https://lichess.org)
- I also like to make lists

**Comment by Ethan37** [comment]
![Markdown 1 2 congrats](https://user-images.githubusercontent.com/54382275/63882852-e4acf000-c9a0-11e9-9d57-ed4c8b578948.PNG)
I ***love*** lists
* I
    + warned
        - you
>##### *wanna buy some lists*
[yes](https://www.amazon.co.uk/s?k=lists&i=stripbooks&ref=nb_sb_noss_1)

**Comment by sebastien741** [comment]
![stat418 congrats screenshot](https://user-images.githubusercontent.com/54560735/63883653-a44e7180-c9a2-11e9-8893-beb6f197b89c.PNG)
**I like tennis**    
[cat](https://www.google.com/search?q=cat&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi98tDZnabkAhUHUa0KHZP1DCEQ_AUIEigB&biw=1920&bih=967#imgrc=P6pyJGdTi6ygcM:)   
I can quote 
> hopefully

**Comment by HannSidney** [comment]
![image](https://user-images.githubusercontent.com/51411477/63884009-669e1880-c9a3-11e9-80d4-387daffbb724.png)

## What I learned in boating school is
1.  ...

# **What i learned in boating school is**

**Comment by Ari-Nicole** [comment]
![Image 8-28-19 at 4 19 PM](https://user-images.githubusercontent.com/54557472/63889831-ce5a6080-c9af-11e9-88b5-dd632322d8a7.jpg)

# Lists
    1. Interesting
    2. Cool
## Also
> Quotes
> 
> In block form

**Comment by lesliand** [comment]
![image](https://user-images.githubusercontent.com/54510202/63891518-5ee67000-c9b3-11e9-8cf1-e43f7e7bb57f.png)

> **Better late than never.**

*- A procrastinator, probably.*

**Comment by aRoberts291404** [comment]
![congratulations](https://user-images.githubusercontent.com/54500137/63897331-c22bce80-c9c2-11e9-9023-3ecf7383afaa.png)

I've been staring at this for **30** minutes, so here's a link to the [Inca](https://en.wikipedia.org/wiki/Inca_Empire) and here's a cat:
![cat](https://user-images.githubusercontent.com/54500137/63897612-be4c7c00-c9c3-11e9-8f63-00abaea4a4c1.png)


\- A human

**Comment by picardph** [comment]
![2019-08-28](https://user-images.githubusercontent.com/37383062/63899270-3ae25900-c9ca-11e9-8080-f39cba36cfc9.png)

Alright guys, if you are using Windows and want to crash your computer just for fun, here is a little program to run!

Here are the steps:
1. Open Notepad
2. Save the file as death.bat (not as a text file).
3. Write the following code in it:
    ```
    open death.bat
    ```
4. Save the file.
5. Double click on the file on your desktop.
6. Congratulations, your computer will be crashing shortly!

If you feel bad for your computer here is a picture of [Mr. Rogers](https://en.wikipedia.org/wiki/Fred_Rogers) to make you feel better. ![](https://upload.wikimedia.org/wikipedia/commons/a/a2/DivaMan_as_Officer_Clemmons.png)

If you have some spare time tonight, [here is a 10 hour video of a man yodeling.](https://www.youtube.com/watch?v=Lxt0_YrQs0M)

Philip Picard

EDIT: I would also like to quote my old pa for some life advice
> Phil, my son, let me teach you something good. You listening boy? Never use water to put out an oil fire, my boy.

**Comment by palazmic** [comment]
<img width="1214" alt="Screen Shot 2019-08-28 at 7 35 56 PM" src="https://user-images.githubusercontent.com/54516240/63899739-07083300-c9cc-11e9-9672-2b227fb66714.png">

![](https://techcrunch.com/wp-content/uploads/2015/08/safe_image.gif?w=1390&crop=1)

I like:
* Doing fun stuff
* Watching netflix
* Playing cuberunner

>This activity was fun and interesting

**Comment by cjlarson0** [comment]
![image](https://user-images.githubusercontent.com/33044471/63901404-69fcc880-c9d2-11e9-8c9a-d7aea40c573d.png)

I am currently multitasking by:
* Finishing this assignment
* Watching the youtube series Sam The Cooking Guy
  * He is making lobster breakfast burritos

His shirt says:
> Make America Cook Again

:crab: :crab: :crab: :crab: :crab: :crab: :crab: 
:ok_hand:

**Comment by jul-carras** [comment]
![image](https://user-images.githubusercontent.com/9213584/63900942-8a2b8800-c9d0-11e9-831f-4236c9328c94.png)

# I MADE IT

* I'm *really* proud of myself :shipit:
    * I'm proud of **all** of us right now, actually. :clap:

Have a picture:
![ ](https://media.giphy.com/media/mQvgeIhdQv7B6/giphy.gif)

**Comment by garlitca** [comment]
[Click here to see my congratulations screen](https://github.com/sta518/discussion/files/3553442/Markdown.Tutorial.pdf)

+ Here is a list of my favorite Netflix shows:
1. The Office 
2. Bates Motel
3. Stranger Things 

I'm posting this *SO* late because I was doing the wrong assignment. 

The most recent URL in my browsing history is [Grand Valley State University](https://www.gvsu.edu/) so I could pay my tuition.

**Comment by WarrenSink** [comment]
@garlitca [nice idea to link to the congrats screen](https://commonmark.org/help/tutorial/99-end.html)

# NUIT BLANCHE

![](http://i.imgur.com/60bts.gif)

**Comment by ejrchurch** [comment]
<img width="706" alt="Screen Shot 2019-08-29 at 7 07 34 AM" src="https://user-images.githubusercontent.com/13522910/63935584-ccce7e00-ca2b-11e9-88f9-6673bf536aac.png">

- point 1
- point 2
    - subpoint a
    - subpoint b

1. item 1
2. item 2
    a. subitem a
    b. subitem b

```
code snippet 1
code snippet 2
```

**Comment by forcev** [comment]
![63730714-73ebc380-c83a-11e9-9c2d-ca3121549bc0 (2)](https://user-images.githubusercontent.com/54407465/63939429-4880f880-ca35-11e9-8857-bf52d566ee37.png)

[Here's a link to some adorable kittens.](https://www.petfinder.com/member/us/mi/grand-rapids/kent-county-animal-shelter-mi296/)

1. Good job everyone
2. Happy first week of school.

**Comment by shyaa23** [comment]
![markdown](https://user-images.githubusercontent.com/35463392/63968010-9e24c780-ca6c-11e9-9b96-1cbb5bce1dc3.PNG)

### Markdown is *Awesome* :thumbsup:

**Comment by ugoagwup** [comment]
![PlacidUgoagwuCongratsScreen](https://user-images.githubusercontent.com/43082783/64131696-55388000-cd98-11e9-9fc8-d0f91ebeacc6.JPG)


**GVSU STA 518 Class**

> Nice tutorial on MarkDown 

[Grand Valley State University](https://www.gvsu.edu)

**Comment by ugoagwup** [comment]
![PlacidUgoagwuCongratsScreen](https://user-images.githubusercontent.com/43082783/64131696-55388000-cd98-11e9-9fc8-d0f91ebeacc6.JPG)

Nice tutorial on MarkDown

**Comment by ugoagwup** [comment]
![PlacidUgoagwuCongratsScreen](https://user-images.githubusercontent.com/43082783/64131696-55388000-cd98-11e9-9fc8-d0f91ebeacc6.JPG)

Nice tutorial on MarkDown
