### ISSUE TITLE
Application 3: Given code not working

### ISSUE THREAD

**Issue by zyskabbie** [sta518/discussion#11]
So I am almost finished application activity 3, I went to finish it today and am getting errors that were not there before.
![image](https://user-images.githubusercontent.com/54541090/67149675-1729e980-f27c-11e9-993f-c6578238cedf.png)

I did not change anything from before when it was working fine and I can't figure out what it is wrong. And I can't finish the application activity because the GSS file is no longer in R. 

I also deleted and re-uploaded the data set, refreshed R, restarted my computer, and googled the error and still couldn't get it to work.

**Comment by dykesb** [comment]
I see that you "figured" this out in the announcement issues repo, but will post here too.

Try re-installing and re-librarying `dplyr` if you experience this issue.
