### ISSUE TITLE
Application Task 3: Repo not being Created

### ISSUE THREAD

**Issue by EricKirkendall** [sta518/discussion#12]
Hello,
When I try to click the link from blackboard to create the repo in GitHub, it finishes creating the repo, but the importing starter code bar never finishes. This happens a lot and does not normally make a difference, but this time when I click the link to go to the repo it is completely empty. In the mean time I will ask for the instructions from my group and starter code.

**Comment by picardph** [comment]
It does not matter if the bar does not finish. It seems to be a bug. It imported the code just fine so you can go ahead and work on it.

From: Eric Kirkendall
Sent: Sunday, October 20, 2019 9:36 AM
To: sta518/discussion
Cc: Subscribed
Subject: [sta518/discussion] Application Task 3: Repo not being Created (#12)

Hello,
When I try to click the link from blackboard to create the repo in GitHub, it finishes creating the repo, but the importing starter code bar never finishes. This happens a lot and does not normally make a difference, but this time when I click the link to go to the repo it is completely empty. In the mean time I will ask for the instructions from my group and starter code.

**Comment by EricKirkendall** [comment]
For clarification because my first comment may have been unclear, there is nothing in the repo that was created. This means that if I create an R studio project from the repo, the project is also empty. There is no instructions file and no rmd file. If I try redownloading the repo from blackboard, it remains empty.

**Comment by dykesb** [comment]
I have added the the starter files to your repo.  I don't know why this happens with GitHub Classroom sometimes.  It is annoying, but a very simple fix!

**Comment by EricKirkendall** [comment]
Awesome Thanks!
