### ISSUE TITLE
Bootstrap between means not working

### ISSUE THREAD

**Issue by maleym** [sta518/discussion#13]
I'm not sure what I'm doing wrong here, but I get an error every time I run this code. First, the error says "Error: A level of the response variable `advfront` needs to be specified for the `success` argument in `specify()`." so I specify "success = "Yes"" and then I get the error "Error: The response variable of `advfront` is not appropriate since 'diff in means' is expecting the response variable to be numeric."

```{r}
diff_boot <- gss3 %>%
  specify(response = advfront, explanatory = polviews) %>%
  generate(reps = 100, type = "bootstrap") %>%
  calculate(stat = "diff in means", order = c("Yes", "No"))
```

I have tried calculating the bootstrap for liberal and conservative separately but I don't understand how to do the bootstrap for the difference in means after that or if that is even what I'm supposed to be doing...

Any help would be wonderful. Thank you :)

**Comment by lesliand** [comment]
Check your ``calculate`` function again. In his example he's asking for a mean, but in the problem we are supposed to find the difference in proportions. There's a different ``stat`` for it.

**Comment by maleym** [comment]
Thank you so much
