### ISSUE TITLE
Bootstrap with 15000 Reps

### ISSUE THREAD

**Issue by EricKirkendall** [sta518/discussion#14]
Hello,
When I change my bootstraps to do 15000 reps instead of 100 it takes forever to knit. As of now my rmd has been knitting for 3 hours straight and it is on the first of the two bootstraps. Is anyone else having this issue?

**Comment by edorn15** [comment]
It was left on a previous issue, but Dr. Dykes said it was okay to do 1500 reps, so do that instead.

**Comment by EricKirkendall** [comment]
Okay thanks!
