### ISSUE TITLE
Activity 3.3 Modeling Issue

### ISSUE THREAD

**Issue by JacobW1998** [sta518/discussion#16]
I'm having an issue trying to write my map function for part 3 of the exercise with using the given snip of code from the instructions. 

by_occupation %>% 
mutate(model = map(nested_data, lm(y ~ model, data = .)))
----
regardless what I put in for my dataset or in place of the period it keeps giving me the error 

* "Object 'y' not found" 

any advice would be greatly appreciated!!

**Comment by dykesb** [comment]
You need a `~` also before your `lm(...)` call.  This lets `map` know that you're using a "recipe":

`mutate(model = map(nested_data, ~ lm(...))`

Also, double check what the nested data column is called in your `by_occupation` data frame.
