### ISSUE TITLE
Question About Application 06

### ISSUE THREAD

**Issue by annie5696** [sta518/discussion#17]
For Application 06, I was confused about the link for the scrape and visualization page for “Gender Pay Gap”.  Are we supposed to scrape the table from the “List of countries by a male to female income ratio” page which has around 168 observations and provides similar visualization?

Although, I did scrap from the link provided in the application, I was also wondering if we have to plot 168 countries or we can use some filters?

**Comment by dykesb** [comment]
Scrape from the male to female income ratio page and make a plot similar to, but not exactly like, that on the gender pay gap page.  Your visualization won't look exactly like the one on the gender pay gap page as it is different information, but assess what the important information that plot is detailing and create something similar with this different information.
