### ISSUE TITLE
Introduce Yourself

### ISSUE THREAD

**Issue by dykesb** [sta518/discussion#2]
I got my B.S. in Statistics from GVSU in '09, then M.S. ('11) and PhD ('16) from Western Michigan.  After graduating, I worked at Husson University (a small private university in Bangor, ME) developing a program and certificate in Data Analytics.

In my free time, I like to go on hikes with Odin (my 9 year old Great Dane) and partner Michele.

**Comment by aaronVillafuerte** [comment]
Aaron Villafuerte
I like pizza
@corinnejay when's our first exam?

**Comment by daceyh123** [comment]
Hello, My name is Hunter Dacey. My "Thing of Interest" is that I have done marching band here at Grand Valley for 4 years. I am neighbors with @grismasinya. I do not have any questions related to the syllabus yet.

**Comment by lesliand** [comment]
@TonyTone1995 I'm Andrew (Drew) Leslie; I graduated from MSU with a BS in microbiology and now getting my master's in Biostats. I've been working at Zoetis in Kalamazoo QC'ing data from Illumina's Infinium microarray platform.

**Comment by JacobW1998** [comment]
Jacob Weishuhn
I Like Volleyball
@nrozema
No Questions Yet

**Comment by KenzieKo** [comment]
Hello I'm Kenzie,
One fun fact about me is that I am a vegetarian.

@KelArndt

**Comment by harmans97** [comment]
Good evening! My name is Sara,  I am a nursing major with a minor in applied statistics going into my fourth year here at GV. I am passionate about traveling and would love to learn French! I plan to go abroad after I graduate to places in Africa. My neighbor is @dianagoodrich. I do not have any questions about the syllabus!

**Comment by adam-hubbell** [comment]
I'm Adam Hubbell, I played the oboe for 4 years, my neighbors are @smbrougham and @maleym, I have no questions.

**Comment by zyskabbie** [comment]
Hey friends! I am Abbie Zysk and am in the last year of the Biostatistics masters program. My favorite sub from Jimmy Johns is #5 the perfect Italian. @latackk @lexdrennan

**Comment by KelArndt** [comment]
Hello, I am Kelly!
I enjoy photographing city-scapes.
@KenzieKo
I have no questions.

**Comment by latackk** [comment]
I am Katie Latack and I am in the biostats program. I like panda bears. @zyskabbie I currently have no questions.

**Comment by TonyTone1995** [comment]
Hello everyone, 

- Name is Tony Ruiz
- I am in the Data Science Master's Program
- My neighbor is @lesliand

**Comment by lexdrennan** [comment]
Hi - I'm Lex. I am....an Australian who somehow landed in Grand Rapids, married and planning to stay put here. It's likely you either won't understand my accent or know what I'm saying anyway, because apparently American and Australian are different langues lol. My hobbies include woodworking and cooking, and watching UFC. @zyskabbie

**Comment by cjlarson0** [comment]
Hi, my name is Connor Larson. I love college football and am a big Michigan fan. 
My neighbor is  @jul-carras

**Comment by smbrougham** [comment]
Hey I'm Sydney Brougham, and I like monster trucks.
@adam-hubbell @corinnejay
No questions yet.

**Comment by shyaa23** [comment]
Hi everyone,
This is shreya and I am currently doing my Masters in Data science and Analytics. One thing that interest me is food :) My neighbor is: @annie5696

**Comment by sageb82** [comment]
Hello, I am Sage.
Big football fan, like to cook, and am learning German.
@KelArndt

**Comment by nrozema** [comment]
I'm Nick Rozema. One interesting thing about me is that I majored in Classics during my undergrad and know some Latin and Ancient Greek. My neighbor is @jacobw1998. No questions at the moment, but we'll see how long that continues.

**Comment by annie5696** [comment]
Hello everyone, I am Anisha shrestha, 
I am a huge food lover and I love to hike in my free time. 
 My neighbor is @shyaa23

**Comment by corinnejay** [comment]
Hi, I'm Corinne Jaskiewicz and I go by Cori!
I just got a dog last May and I like to travel
@aaronVillafuerte @smbrougham
No questions yet!

**Comment by ejrchurch** [comment]
Elliott Church
I'm interested in computational methods for natural language processing (NLP). If you are, too, please let me know!
@hjaeckle
No question about the Syllabus.

**Comment by hjaeckle** [comment]
My name is Heidi Jaeckle. I recently moved from Arkansas. My neighbor is @ejrchurch. No questions.

**Comment by grismasinya** [comment]
I am Grisma Sinya and this is my second year in Data Science program. I'm neighbours with @daceyh123

**Comment by dianagoodrich** [comment]
I am Diana, I'm currently in my last semester at GVSU to get my degree in Actuarial Science. My neighbor is @harmans97. I have no questions about the syllabus.

**Comment by Ting123go** [comment]
Hello, my name is Ting, a graduate student in Data Science and Analytics Program in GVSU. I'm interested in traveling and my neighbor is @chitzinwin @sageb82

**Comment by jul-carras** [comment]
Hi! I'm Julian. I'm in the DataSci program with about another year to go. @cjlarson0 is hanging out near me. 

I'm originally from the Bronx and went to Michigan for undergrad in actuarial science. This past weekend I dug a hole at the beach that could hold a full grown man. 

No questions yet on the syllabus.

**Comment by maleym** [comment]
Morgan Maley
I really enjoy traveling, mostly camping. My favorite trip so far has been to Yellowstone.
@adam-hubbell

**Comment by chitzinwin** [comment]
Hi, Chit Zin Win, a DataScience student. Excited about community style class. My neighbor is @Ting123go , here we go

**Comment by PorterSmash** [comment]
My name is Alex Porter and I am a Data Science minor. 

I enjoy outdoor hobbies in my free time like fishing and rock climbing.
My neighbor is @despresj

**Comment by edorn15** [comment]
Emily Dorn
I have two sets of twins in my immediate family. 
@nlj2014

**Comment by hawkeral** [comment]
Hello! My name is Alyssa Hawker.
I am one of the Drum Majors in the Laker Marching Band! My neighbor is @palazmic .

**Comment by despresj** [comment]
Hello, I am Joe Despres Interested in economics and statistics. @PorterSmash .

**Comment by nlj2014** [comment]
Hi, I am Natalie Johnson. I completed my undergrad in Biomedical science at CMU. I am a grad student in biostats. My neighbor is @edorn15. I am excited for this course and I do not have any questions about the syllabus yet.

**Comment by picardph** [comment]
Howdy, I'm Philip (or Phil). One thing of interest about me is that I have a commercial pilot's license.
Hello @danno3321.
No questions about the syllabus.

**Comment by danno3321** [comment]
My name is Adam Weaver.
I'm an Eagle Scout and know how to ride a unicycle, though I am out of practice.
@picardph

**Comment by forcev** [comment]
Hi, I'm Victoria Force. My 'interesting fact' is that I teach traditional Irish dancing classes. 
Looking forward to another class with @rbaxter231 and @hannsidney
No questions about the syllabus at this time.

**Comment by rbaxter231** [comment]
Hi! 
I am Rachel Baxter. 
I have 3 pets (2 dogs and 1 cat). 
@forcev @hannsidney 
No questions.

**Comment by HannSidney** [comment]
Sidney Hann
I like playing tennis. My neighbors are @forcev and @rbaxter231. No questions about the syllabus

**Comment by palazmic** [comment]
My name is Michael Palazzolo. I am in the Biostatistics program. I enjoy being outdoors and doing things like wake surfing, and skiing in the winter. My neighbor is @hawkeral.

**Comment by degraafn** [comment]
Hello.  Nate DeGraaf here.  I enjoy live music and growing my own food.   My neighbor is @ortizel

**Comment by EricKirkendall** [comment]
My name is Eric Kirkendall and I am a psychology major with a stats minor.
My neighbor is @abanninga

**Comment by aRoberts291404** [comment]
I am Austin Roberts, I intend to go to medical school after graduation. My neighbor is @garlitca and I do not have any questions regarding the Syllabus and Course Policies yet.

**Comment by SBennett95** [comment]
Hi my name is Stephen Bennett. I'm an undergraduate statistics major and I have an economics minor. My neighbor is @ari-nicole.

**Comment by sebastien741** [comment]
Hi I am sebastien and I like tennis. @mattphad

**Comment by ortizel** [comment]
Hi, my name is Liz Ortiz. I like playing soccer.
@degraafn

**Comment by abanninga** [comment]
Hi I'm Alaine! I have a 17 lb cat named Doug. My neighbor is @erickirkendall

**Comment by mattphad** [comment]
My name is Matt Phad 
I watch a lot of TV
@sebastien741

**Comment by WarrenSink** [comment]
Hey, I'm Warren, and I'm a CMB major. I live in Eastown.  @degraafm, I don't have any questions about the syllabus, but I'll let you know if I do.

**Comment by Carl-Wilson96** [comment]
My name is Carl Wilson,
I enjoy fishing.
My neighbors are @ForceV and @HannSidney.
Questions regarding syllabus: N/A

**Comment by garlitca** [comment]
My name is Alayna (Ally) Garlitch. I am an HR major and a statistics minor. I commute an hour to class. My neighbor is @aRoberts291404.

**Comment by Ari-Nicole** [comment]
Hi, I am Arielle (Arr-Ree-Ell) Roberson. I go by Ari (Arr-Ree). I'm a Math and Statistics double major. I like to dance but I wouldn't say I'm very skilled.  My neighbor is @SBennett95 .

**Comment by Ethan37** [comment]
My name is Ethan Brown and I am a statistics major with a computer science minor. My neighbors username is @ugoagwup.

**Comment by ugoagwup** [comment]
Hello! My name is Placid Ugoagwu. I am a Masters in Biostatistics year 2 student. I have worked as a Clinical Data Manager in the last 12years of my life. My user name is @ugoagwup. I am hoping to have a better learning experience in R. My neighbor's user name is @ethan37
