### ISSUE TITLE
Exploratory Data Analysis Primer not working

### ISSUE THREAD

**Issue by TonyTone1995** [sta518/discussion#4]
Working through the Exploratory Data Analysis primer in Rstudio cloud and was not able to advance through the table of contents by clicking the "continue" button. The only way to get through the sections was to click on them through the table of contents, however it does not show that you completed the activities in that section. Is anyone else having this issue? 
[https://rstudio.cloud/learn/primers/3.1](url)

**Comment by despresj** [comment]
Yeah, worked fine after restarting my computer

**Comment by dykesb** [comment]
Refreshing your page might be able to help with this too (rather than needing to do an entire machine restart).  These primers are built in [learnr](https://rstudio.github.io/learnr/) and hosted on a Shiny Server, so there might just be some connection lag.
