### ISSUE TITLE
application 2

### ISSUE THREAD

**Issue by sebastien741** [sta518/discussion#5]
1) I don't understand what the question is for 2.3: Calculate the relative frequency of post-evolution stronger attack based on the pre-evolution stronger attack.
I created a bar plot with the pre-evolution and post evolution strong attack (using their name) so you can see if the their strong attack have changed through the evolution. is it what you expect?
2) for question 2.7: What characteristics correspond to an evolved Pokémon with a high combat power? You do not need to come up with an exhaustive list, but you should walk through your reasoning as you answer this question. Include all relevant summary statistics and visualizations.
I think doing some regressions seem to be the best way to answer this question (but we havent seen it yet). I see that there is a variable for combat power (dependent variable), so should I just run regressions with some variables to see which ones are statistically significant? maybe also create some scatter plots to check the linearity condition? but I do not see how summary statistics could help me here.

**Comment by dykesb** [comment]
1. Another way to read this is, "For each pre-evo attack, what is the percentage breakdown of each post-Evo attack?" This could be a table or plot.
2. You should look at pairings of variables that you think might impact cp and explore if these contribute to higher values. Again, tables or plots will help you answer this.

**Comment by dykesb** [comment]
1. Another way to read this is, "For each pre-evo attack, what is the percentage breakdown of each post-Evo attack?" This could be a table or plot.
2. Use tables/plots and reasoning from the variable descriptions.  This wouldn't be appropriate for p-values since you have population information.

**Comment by sebastien741** [comment]
Ok that helps. thank you
