### ISSUE TITLE
push issue

### ISSUE THREAD

**Issue by sebastien741** [sta518/discussion#6]
I have completed the application but it does not let me push and it give me an error message that I have not seen before: 

To https://github.com/sta518/application02-sebastien741.git  ! [rejected]        HEAD -> master (fetch first) error: failed to push some refs to 'https://github.com/sta518/application02-sebastien741.git' hint: Updates were rejected because the remote contains work that you do hint: not have locally. This is usually caused by another repository pushing hint: to the same ref. You may want to first integrate the remote changes hint: (e.g., 'git pull ...') before pushing again. hint: See the 'Note about fast-forwards' in 'git push --help' for details. 

I have tried a few things but nothing has worked so far. What should I do?

**Comment by dykesb** [comment]
What "few things" have you tried?

**Comment by sebastien741** [comment]
I am good, it got pushed last night. I went to a website where they said that I should try to pull with git pull origin master -f then push with git push origin master -f. it was not enough so I did other things like taking care of merging issues and it finally worked.
