### ISSUE TITLE
application 2 - 2.2 

### ISSUE THREAD

**Issue by maleym** [sta518/discussion#7]
Hi class, 

I'm having trouble with 2.2. My code for the histogram is below, I don't know how to create bars based on species with two bars for each. Could someone provide some guidance?

Thank you

```{r}
ggplot(poke_attack, aes(x=attack_weak_value, color=attack_weak, fill=attack_weak)) +
  geom_histogram() + coord_flip() +
labs(title="Pre-evolution weaker attack of the Pokemon", subtitle= "by species", x="Frequency", y = "Species") +
  theme_classic()
```

**Comment by maleym** [comment]
Oh whoops - here are the websites/sources Ive already referenced...
https://stackoverflow.com/questions/50810198/rotating-histogram-horizontally-in-r
http://www.sthda.com/english/wiki/ggplot2-histogram-plot-quick-start-guide-r-software-and-data-visualization#change-histogram-plot-colors-by-groups
https://www.google.com/search?q=r+histogram+multiple+columns&sa=X&ved=2ahUKEwidqL3h2e_kAhURXKwKHXDxDGUQ1QIoBHoECAoQBQ&biw=1280&bih=666

**Comment by jul-carras** [comment]
Hey Morgan,

I actually didn't use `geom_histogram`, but `geom_col`. I calculated the frequency counts after grouping on  species and attack_weak. I know in `geom_col`, `position = "dodge"` gives the separated columns.

**Comment by dykesb** [comment]
Remember that histograms are for numeric variables. Try looking for information on bar charts instead.

**Comment by lexdrennan** [comment]
I used geom_bar with position="dodge". The position=dodge is the critical part.

**Comment by maleym** [comment]
thank you!
