### ISSUE TITLE
location of meeting prep assignments

### ISSUE THREAD

**Issue by lexdrennan** [sta518/discussion#8]
Hi all - I feel stupid asking this, but I'm struggling to find where I should go to read the meeting prep tasks. Can anyone point me in the right direction? I can't find anything useful from Blackboard and I'm not having any luck hunting around our git hub. Thanks!

**Comment by ejrchurch** [comment]
Hi, Lex. https://github.com/sta518/announcements/issues

**Comment by lexdrennan** [comment]
thanks @ejrchurch - I was hunting in the wrong place!
