### ISSUE TITLE
what package to use for the str_view function

### ISSUE THREAD

**Issue by zyskabbie** [sta518/discussion#9]
Does anyone know what package I need to install to use str_view()? I already have tidyverse and stringr, but I got this when I tried to use str_view():

 "Error: htmlwidgets package required for str_view(). Please install.packages("htmlwidgets") to use this functionality."

I then tried to install htmlwidgets and got their error package not found. I then googled what package I needed and it said stringr.....which I already have. I am just working my way through the book so it's not urgent but I am confused as to why it is not working. Thanks!

**Comment by dykesb** [comment]
Are you installing or library-ing htmlwidgets when you get "package not found"?  Try restarting your R session (Session drop down menu) and trying again.  If you still get an error, attach a screen shot of your *Console*.
